### ISSUE TITLE
aria-hidden display:none

### ISSUE THREAD

**Issue by thamas** [rvk-utd/hanna#1]
```css
[aria-hidden][aria-hidden="true"], [hidden][hidden] {
  display: none;
}
```
This is a bug! `aria-hidden="true"` is not for hiding sg from the page totally. It is for keeping it visible while hiding it from screen readers. 

Applying a `display: none` rule is a very bad idea IMHO and I do not understand what could be the reason for it!
